version: "2.1"
services:
  mysql-biouml:
    image: mysql:5
    container_name: mysql-biouml2
    environment:
         - MYSQL_ROOT_PASSWORD=biouml
         - MYSQL_DATABASE=bioumlsupport2
         - MYSQL_USER=bioumlsupport2
         - MYSQL_PASSWORD=bioumlsupport2
    restart: unless-stopped
    expose:
      - 3306
    ports:
      #- 127.0.0.1:3306:3306
      - 3306:3306
    volumes:
      - ${BIOUML_RUN_DIR}/mysqld.conf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ${BIOUML_SUPPORT_DUMP}:/docker-entrypoint-initdb.d/bioumlsupport2.dump.sql
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - /data:/data
  bioumlweb:
    #image: tomcat:9-jdk21-corretto
    image: tomcat:9-jdk21
    container_name: bioumlweb-biouml2
    restart: unless-stopped 
    environment:
      - CATALINA_OPTS=-Djava.security.egd=file:/dev/./urandom
      - JAVA_OPTS=
        -DDOCKER_NETWORK_NAME=${COMPOSE_PROJECT_NAME}_default
        -DDOCKER_BIOUML_RESOURCES=${BIOUML_SERVER_ON_HOST_DIR}/resources
        -Djava.awt.headless=true
        -Dfile.encoding=UTF-8
        -Xdebug -Xrunjdwp:transport=dt_socket,address=*:8000,server=y,suspend=n
        --add-opens java.base/java.net=ALL-UNNAMED
    expose:
      - 8010
      - 8020
    ports:
      - 8010:8080
      - 8020:8000
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - ${BIOUML_SERVER_ON_HOST_DIR}:/BioUML_Server
      - ${BIOUML_RUN_DIR}/server.lcf:/BioUML_Server/conf/server.lcf:ro
      - ${BIOUML_RUN_DIR}/security.properties:/BioUML_Server/conf/security.properties
      - ${BIOUML_RUN_DIR}/security.properties:/BioUML_Server/repo/security.properties:ro
      - ${BIOUML_RUN_DIR}/plugins:/BioUML_Server/plugins
      - ${BIOUML_RUN_DIR}/configuration:/BioUML_Server/configuration
      - ${BIOUML_RUN_DIR}/config.ini:/BioUML_Server/configuration/config.ini
      - ${BIOUML_RUN_DIR}/biouml.policy:/root/.java.policy
      - ${BIOUML_RUN_DIR}/preferences.xml:/BioUML_Server/preferences.xml
      - ${BIOUML_WAR}:/usr/local/tomcat/webapps/biouml.war
      - ${BIOUMLWEB_WAR}:/usr/local/tomcat/webapps/bioumlweb.war
      - ${BIOUML_RUN_DIR}/favicon.ico:/usr/local/tomcat/webapps/ROOT/favicon.ico
      - ${BIOUML_RUN_DIR}/docker.out/logs:/usr/local/tomcat/logs
