/* Generated By:JavaCC: Do not edit this line. AntimonyParserTreeConstants.java Version 7.0.10 */
package biouml.plugins.antimony.astparser;

public interface AntimonyParserTreeConstants
{
    public int JJTSTART = 0;
    public int JJTVOID = 1;
    public int JJTIMPORT = 2;
    public int JJTTEXT = 3;
    public int JJTFUNCTION = 4;
    public int JJTEOL = 5;
    public int JJTSEMICOLON = 6;
    public int JJTSYMBOL = 7;
    public int JJTREGULARFORMULAELEMENT = 8;
    public int JJTCOMMA = 9;
    public int JJTMODEL = 10;
    public int JJTGLOBAL = 11;
    public int JJTAS = 12;
    public int JJTPROPERTY = 13;
    public int JJTEQUAL = 14;
    public int JJTUNIT = 15;
    public int JJTUNITFORMULA = 16;
    public int JJTDELETE = 17;
    public int JJTSYMBOLTYPE = 18;
    public int JJTVARORCONST = 19;
    public int JJTIN = 20;
    public int JJTEQUALZERO = 21;
    public int JJTEQUATION = 22;
    public int JJTSUBSYMBOL = 23;
    public int JJTCONNECTIONCONVERSIONFACTOR = 24;
    public int JJTCOLON = 25;
    public int JJTCOLONEQUAL = 26;
    public int JJTRATEEQUAL = 27;
    public int JJTAT = 28;
    public int JJTAFTER = 29;
    public int JJTELSE = 30;
    public int JJTASSERT = 31;
    public int JJTPRIORITY = 32;
    public int JJTUSEVALUESFROMTRIGGERTIME = 33;
    public int JJTPERSISTENT = 34;
    public int JJTTRIGGERINITIALVALUE = 35;
    public int JJTIS = 36;
    public int JJTSUBTYPE = 37;
    public int JJTHAS = 38;
    public int JJTRELATIONSHIPTYPE = 39;
    public int JJTREACTIONTITLE = 40;
    public int JJTPLUS = 41;
    public int JJTAND = 42;
    public int JJTOR = 43;
    public int JJTNOT = 44;
    public int JJTREACTANT = 45;
    public int JJTPRODUCT = 46;
    public int JJTSTOICHIOMETRY = 47;
    public int JJTREACTIONTYPE = 48;
    public int JJTCONVERSIONFACTOR = 49;
    public int JJTSPECIALFORMULA = 50;
    public int JJTCOMMENT = 51;


    public String[] jjtNodeName = {"Start", "void", "Import", "Text", "Function", "EOL", "Semicolon", "Symbol", "RegularFormulaElement",
            "Comma", "Model", "Global", "As", "Property", "Equal", "Unit", "UnitFormula", "Delete", "SymbolType", "VarOrConst", "In",
            "EqualZero", "Equation", "SubSymbol", "ConnectionConversionFactor", "Colon", "ColonEqual", "RateEqual", "At", "After", "Else",
            "Assert", "Priority", "UseValuesFromTriggerTime", "Persistent", "TriggerInitialValue", "Is", "Subtype", "Has",
            "RelationshipType", "ReactionTitle", "Plus", "And", "Or", "Not", "Reactant", "Product", "Stoichiometry", "ReactionType",
            "ConversionFactor", "SpecialFormula", "Comment",};
}
/* JavaCC - OriginalChecksum=2b5d5e3eff25f4ad82d96e91ca60afa8 (do not edit this line) */
