/* Generated By:JJTree: Do not edit this line. AstAssert.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstAssert extends SimpleNode
{
    public AstAssert(int id)
    {
        super(id);
    }

    public AstAssert(AntimonyParser p, int id)
    {
        super(p, id);
    }

    public String toString()
    {
        return "assert";
    }

}
/* JavaCC - OriginalChecksum=86d6b2afb9860228e67a385c2f1ac915 (do not edit this line) */
