/* Generated By:JJTree: Do not edit this line. AstComma.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstComma extends SimpleNode
{
    public AstComma(int id)
    {
        super(id);
    }

    public AstComma(AntimonyParser p, int id)
    {
        super(p, id);
    }

    public String toString()
    {
        return ",";
    }

}
/* JavaCC - OriginalChecksum=2166f90ec17621d0a8f6d7e36dda8cc2 (do not edit this line) */
