/* Generated By:JJTree: Do not edit this line. AstElse.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstElse extends SimpleNode
{
    public AstElse(int id)
    {
        super(id);
    }

    public AstElse(AntimonyParser p, int id)
    {
        super(p, id);
    }

    public String toString()
    {
        return "else";
    }

}
/* JavaCC - OriginalChecksum=1a7cb6c8dabdacbaa774220ad294d55d (do not edit this line) */
