/* Generated By:JJTree: Do not edit this line. AstEqualZero.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstEqualZero extends SimpleNode
{

    public AstEqualZero(int id)
    {
        super(id);
    }

    public AstEqualZero(AntimonyParser p, int id)
    {
        super(p, id);
    }

    String view = "0 =";

    public String toString()
    {
        return view;
    }

}
/* JavaCC - OriginalChecksum=68202eb0d3522b337fac8e960136f31f (do not edit this line) */
