/* Generated By:JJTree: Do not edit this line. AstHas.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstHas extends SimpleNode
{
    public AstHas(int id)
    {
        super(id);
    }

    public AstHas(AntimonyParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "has";
    }

    public String getUnitName()
    {
        for( int i = 0; i < this.jjtGetNumChildren(); i++ )
            if( this.jjtGetChild(i) instanceof AstSymbol )
                return ( (AstSymbol)this.jjtGetChild(i) ).getName();
        return null;
    }

    public void setUnitName(String name)
    {
        for( int i = 0; i < this.jjtGetNumChildren(); i++ )
            if( this.jjtGetChild(i) instanceof AstSymbol )
                ( (AstSymbol)this.jjtGetChild(i) ).setName(name);
    }

}
/* JavaCC - OriginalChecksum=19f6254d656f723df4fe1da53f564ebf (do not edit this line) */
