/* Generated By:JJTree: Do not edit this line. AstNot.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstNot extends AstFormulaElement
{
    public AstNot(int id)
    {
        super(id);
    }

    public AstNot(AntimonyParser p, int id)
    {
        super(p, id);
    }

    public String toString()
    {
        return "not";
    }

}
/* JavaCC - OriginalChecksum=8b0e2d5819858278f80121c3a6c663c2 (do not edit this line) */
