/* Generated By:JJTree: Do not edit this line. AstPlus.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstPlus extends AstFormulaElement
{
    public AstPlus(int id)
    {
        super(id);
    }

    public AstPlus(AntimonyParser p, int id)
    {
        super(p, id);
    }

    public String toString()
    {
        return "+";
    }
}
/* JavaCC - OriginalChecksum=1bc97d6e3aff1998f1dde95ac6c91d7a (do not edit this line) */
