/* Generated By:JJTree: Do not edit this line. AstReactionType.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstReactionType extends SimpleNode
{
    public final static String REVERSIBLE = "->";
    public final static String IRREVERSIBLE = "=>";
    public final static String UNKNOWN_MODIFIER = "-(";
    public final static String INHIBIOR = "-|";
    public final static String ACTIVATOR = "-o";

    public AstReactionType(int id)
    {
        super(id);
    }

    public AstReactionType(AntimonyParser p, int id)
    {
        super(p, id);
    }

    private String type = "";

    public String getType()
    {
        return type;
    }

    public void setType(String type)
    {
        this.type = type;
    }

    public String toString()
    {
        return type;
    }

    public boolean isReversible()
    {
        if( type.contains("-") && type.contains(">") )
            return true;
        return false;
    }

    public void setType(Token token) throws ParseException
    {
        String sign = token.image;
        if( ! ( sign.equals(">") || sign.equals("|") || sign.equals("o") || sign.equals("(") ) )
            throw new ParseException("Incorrect reaction type");
        String prefix = "";
        if( token.specialToken != null )
            prefix = token.specialToken.toString();
        this.type = "-" + prefix + sign;
    }
}
/* JavaCC - OriginalChecksum=52d003bc7994ab8eddbdf7a6a7d51860 (do not edit this line) */
