/* Generated By:JJTree: Do not edit this line. AstRelationshipType.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstRelationshipType extends SimpleNode
{
    public AstRelationshipType(int id)
    {
        super(id);
    }

    public AstRelationshipType(AntimonyParser p, int id)
    {
        super(p, id);
    }

    private String name;

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    @Override
    public String toAntimonyString()
    {
        return name;
    }

}
/* JavaCC - OriginalChecksum=c0898855582b82193389056fb5c8e714 (do not edit this line) */
