/* Generated By:JJTree: Do not edit this line. AstRegularFormulaElement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstRegularFormulaElement extends AstFormulaElement
{
    public AstRegularFormulaElement(int id)
    {
        super(id);
    }

    public AstRegularFormulaElement(AntimonyParser p, int id)
    {
        super(p, id);
    }

    private String element;
    private boolean isNumber = false;
    private boolean isString = false;

    public void setElement(String element)
    {
        this.element = element;
    }

    public void setElement(boolean element)
    {
        if( element )
            this.element = "true";
        else
            this.element = "false";
    }


    public String toString()
    {
        return element;
    }

    @Override
    public boolean isNumber()
    {
        return isNumber;
    }

    @Override
    public boolean isString()
    {
        return isString;
    }

    public void setNumber(boolean isNumber)
    {
        this.isNumber = isNumber;
    }

    public void setString(boolean isString)
    {
        this.isString = isString;
    }
}
/* JavaCC - OriginalChecksum=9340782d3695abcd5ecc75d3344cd604 (do not edit this line) */
