/* Generated By:JJTree: Do not edit this line. AstSubtype.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstSubtype extends SimpleNode
{
    public AstSubtype(int id)
    {
        super(id);
    }

    public AstSubtype(AntimonyParser p, int id)
    {
        super(p, id);
    }

    public String toString()
    {
        return "subtype";
    }

}
/* JavaCC - OriginalChecksum=a0c23a726dcf2f0dfef3661e0b20916a (do not edit this line) */
