/* Generated By:JJTree: Do not edit this line. AstSubSymbol.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

import ru.biosoft.util.TextUtil2;

public class AstSubSymbol extends AstSymbol
{
    public AstSubSymbol(int id)
    {
        super(id);
    }

    public AstSubSymbol(AntimonyParser p, int id)
    {
        super(p, id);
    }


    private String[] chainNames;

    @Override
    public void setName(String name)
    {
        this.name = name;
        chainNames = TextUtil2.split(name, '.');
    }

    @Override
    public String[] getChainNames()
    {
        return chainNames;
    }
    @Override
    public String getNameInSubDiagram()
    {
        return chainNames[chainNames.length - 1];
    }
}
/* JavaCC - OriginalChecksum=9397593e32eb5ebbeab9fd77b794df1d (do not edit this line) */
