/* Generated By:JJTree: Do not edit this line. AstUnitFormula.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstUnitFormula extends SimpleNode
{

    private String formula = "";

    public AstUnitFormula(int id)
    {
        super(id);
    }

    public AstUnitFormula(AntimonyParser p, int id)
    {
        super(p, id);
    }

    public void setFormula(String formula)
    {
        this.formula = formula;
    }

    @Override
    public String toAntimonyString()
    {
        return "";
    }

    public String getFormula()
    {
        StringBuilder formula = new StringBuilder("");
        for( int i = 0; i < this.jjtGetNumChildren(); i++ )
        {
            Token firstToken = ( (SimpleNode)this.jjtGetChild(i) ).jjtGetFirstToken();
            if( firstToken != null && firstToken.specialToken != null )
                formula.append(firstToken.specialToken);
            formula.append(jjtGetChild(i).toString());
        }
        return formula.toString();
    }

}
/* JavaCC - OriginalChecksum=6caa5b59faea8f636ebeda9edaaa219e (do not edit this line) */
