/* Generated By:JJTree: Do not edit this line. AstUseValuesFromTriggerTime.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser;

public class AstUseValuesFromTriggerTime extends SimpleNode
{
    public AstUseValuesFromTriggerTime(int id)
    {
        super(id);
    }

    public AstUseValuesFromTriggerTime(AntimonyParser p, int id)
    {
        super(p, id);
    }

    public Boolean getValue() throws ParseException
    {
        for( int i = 0; i < this.jjtGetNumChildren(); i++ )
            if( this.jjtGetChild(i) instanceof AstRegularFormulaElement )
            {
                return Boolean.parseBoolean( ( (AstRegularFormulaElement)this.jjtGetChild(i) ).toString());
            }
        throw new ParseException("Invalid AST tree structure at line: " + firstToken.beginLine + ", column: " + firstToken.beginColumn
                + ". Was expected one of: 'true', 'false'");
    }

    public void setValue(boolean value)
    {
        for( int i = 0; i < this.jjtGetNumChildren(); i++ )
            if( this.jjtGetChild(i) instanceof AstRegularFormulaElement )
            {
                ( (AstRegularFormulaElement)this.jjtGetChild(i) ).setElement(value);
                break;
            }
    }


    public String toString()
    {
        return "fromTrigger";
    }
}
/* JavaCC - OriginalChecksum=8444a6b3c5fdc16d8a0b9706afd1ab90 (do not edit this line) */
