package biouml.plugins.simulation;

import java.util.logging.Logger;
import biouml.model.Diagram;

public abstract class Preprocessor
{
    protected Logger log = Logger.getLogger(Preprocessor.class.getName());
    
    public static final String AUTOGENERATED_VAR = "autogenerated";

    public abstract Diagram preprocess(Diagram diagram) throws Exception;

    /**
     * Determine whether this preprocessor should be applied to the given diagram
     * @param diagram
     * @return
     */
    public boolean accept(Diagram diagram)
    {
        return true;
    }


}
