/* Generated By:JavaCC: Do not edit this line. BionetgenParserTreeConstants.java Version 5.0 */
package biouml.plugins.bionetgen.bnglparser;

public interface BionetgenParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEOL = 1;
  public int JJTSIMPLEELEMENT = 2;
  public int JJTVOID = 3;
  public int JJTSPECIES = 4;
  public int JJTCOMMENT = 5;
  public int JJTDESCRIPTION = 6;
  public int JJTMODEL = 7;
  public int JJTLIST = 8;
  public int JJTPARAMETER = 9;
  public int JJTMOLECULETYPE = 10;
  public int JJTSEEDSPECIE = 11;
  public int JJTOBSERVABLE = 12;
  public int JJTREACTION = 13;
  public int JJTRATELAW = 14;
  public int JJTADDITION = 15;
  public int JJTACTION = 16;
  public int JJTACTIONPARAMETER = 17;
  public int JJTHASH = 18;
  public int JJTEXPRESSION = 19;
  public int JJTFUNCTION = 20;
  public int JJTCONSTANT = 21;
  public int JJTLABEL = 22;


  public String[] jjtNodeName = {
    "Start",
    "EOL",
    "SimpleElement",
    "void",
    "Species",
    "Comment",
    "Description",
    "Model",
    "List",
    "Parameter",
    "MoleculeType",
    "SeedSpecie",
    "Observable",
    "Reaction",
    "RateLaw",
    "Addition",
    "Action",
    "ActionParameter",
    "Hash",
    "Expression",
    "Function",
    "Constant",
    "Label",
  };
}
/* JavaCC - OriginalChecksum=5b55d3d1a0d007082dcbfe8014e9cf22 (do not edit this line) */
