/* Generated By:JJTree: Do not edit this line. BNGAction.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=BNG,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.bionetgen.bnglparser;

public class BNGAction extends SimpleNode
{
    public BNGAction(int id)
    {
        super(id);
    }

    public BNGAction(BionetgenParser p, int id)
    {
        super(p, id);
    }
}
/* JavaCC - OriginalChecksum=40d6e25bdc30a25161d8b4b62551df83 (do not edit this line) */
