/* Generated By:JJTree: Do not edit this line. BNGActionParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=BNG,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.bionetgen.bnglparser;

public class BNGActionParameter extends SimpleNode
{
    public BNGActionParameter(int id)
    {
        super(id);
    }

    public BNGActionParameter(BionetgenParser p, int id)
    {
        super(p, id);
    }
}
/* JavaCC - OriginalChecksum=0e017901fa8908b15982416dab4c2cff (do not edit this line) */
