/* Generated By:JJTree: Do not edit this line. BNGComment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=BNG,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.bionetgen.bnglparser;

public class BNGComment extends SimpleNode
{
    @Override
    public void setName(String name)
    {
        if( name.startsWith("# ") )
            this.name = name;
        else
            this.name = "# " + name;
        if(firstToken == null)
            firstToken = new Token();
        firstToken.image = this.name;
    }
    
    public BNGComment(int id)
    {
        super(id);
    }

    public BNGComment(BionetgenParser p, int id)
    {
        super(p, id);
    }
}
/* JavaCC - OriginalChecksum=cb58a2b70ec81bd217e1123ecb69d3e6 (do not edit this line) */
