/* Generated By:JJTree: Do not edit this line. BNGDescription.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=BNG,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.bionetgen.bnglparser;

public class BNGDescription extends SimpleNode
{
    @Override
    public String toBNGString()
    {
        return "";
    }

    public BNGDescription(int id)
    {
        super(id);
    }

    public BNGDescription(BionetgenParser p, int id)
    {
        super(p, id);
    }
}
/* JavaCC - OriginalChecksum=bd0ce9a63f11478f043c89762e5cff54 (do not edit this line) */
