/* Generated By:JJTree: Do not edit this line. BNGExpression.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=BNG,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.bionetgen.bnglparser;

public class BNGExpression extends SimpleNode
{
    public BNGExpression(int id)
    {
        super(id);
    }

    public BNGExpression(BionetgenParser p, int id)
    {
        super(p, id);
    }

    @Override
    public void transferSpecialTokens(SimpleNode source)
    {
        int length = Math.min(jjtGetNumChildren(), source.jjtGetNumChildren());
        if( length != 0 )
        {
            for( int i = 0; i < length; i++ )
                ( (SimpleNode)children[i] ).transferSpecialTokens((SimpleNode)source.jjtGetChild(i));
        }
        else if( jjtGetNumChildren() != 0 )
        {
            ( (SimpleNode)children[0] ).transferSpecialTokens(source);
        }
        else
            super.transferSpecialTokens(source);
    }

    public String generateFormula()
    {
        return getFullName();
    }

}
/* JavaCC - OriginalChecksum=e9ea70a0fdcce2e447c02eb7c7bfdcc0 (do not edit this line) */
