/* Generated By:JJTree: Do not edit this line. BNGEOL.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=BNG,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.bionetgen.bnglparser;

public class BNGEOL extends SimpleNode
{
    public final static String EOL = "\n";

    public BNGEOL(int id)
    {
        super(id);
        name = EOL;
    }

    public BNGEOL(BionetgenParser p, int id)
    {
        super(p, id);
        name = EOL;
    }
}
/* JavaCC - OriginalChecksum=b75e68f984228ee3590bcd9b10027e81 (do not edit this line) */
