/* Generated By:JJTree: Do not edit this line. BNGHash.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=BNG,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.bionetgen.bnglparser;

public class BNGHash extends SimpleNode
{
    public BNGHash(int id)
    {
        super(id);
    }

    public BNGHash(BionetgenParser p, int id)
    {
        super(p, id);
    }
}
/* JavaCC - OriginalChecksum=29a67e4e0a45d85d498bc3bea8444195 (do not edit this line) */
