/* Generated By:JJTree: Do not edit this line. BNGRateLaw.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=BNG,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.bionetgen.bnglparser;

import biouml.plugins.bionetgen.diagram.BionetgenConstants;

public class BNGRateLaw extends SimpleNode
{
    protected String type = BionetgenConstants.DEFAULT;
    public String getType()
    {
        return type;
    }

    public void setType(String type)
    {
        this.type = type;
    }

    /**
     * Transfers special tokens from BNGRateLaw to BNGRateLaw
     * (transfers child special tokens too)
     * @param sourceLaw
     */
    public void transferRateLawSpecialTokens(BNGRateLaw sourceLaw)
    {
        int length = Math.min(jjtGetNumChildren(), sourceLaw.jjtGetNumChildren());
        if( type.equals(sourceLaw.getType()) )
        {
            for( int i = 0; i < length; i++ )
                ( (SimpleNode)children[i] ).transferSpecialTokens((SimpleNode)sourceLaw.jjtGetChild(i));
        }
        else if( length > 0 )
            ( (SimpleNode)children[0] ).transferSpecialTokens((SimpleNode)sourceLaw.jjtGetChild(0));
    }

    public BNGRateLaw(int id)
    {
        super(id);
    }

    public BNGRateLaw(BionetgenParser p, int id)
    {
        super(p, id);
    }
}
/* JavaCC - OriginalChecksum=19760138dd68c3062e024b91328383fa (do not edit this line) */
