/* Generated By:JJTree: Do not edit this line. BNGSpecies.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=BNG,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.bionetgen.bnglparser;

public class BNGSpecies extends SimpleNode
{
    @Override
    public String toBNGString()
    {
        return "";
    }

    @Override
    public void transferSpecialTokens(SimpleNode node)
    {
        if( jjtGetNumChildren() != 0 )
            ( (SimpleNode)children[0] ).transferSpecialTokens(node);
        else
            super.transferSpecialTokens(node);
    }

    public BNGSpecies(int id)
    {
        super(id);
    }

    public BNGSpecies(BionetgenParser p, int id)
    {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=dd34452c4b59f1dc28570b87a9f0b1b7 (do not edit this line) */
