/* Generated By:JJTree: Do not edit this line. BNGStart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=BNG,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.bionetgen.bnglparser;

public class BNGStart extends SimpleNode
{
    public BNGModel getModel()
    {
        for( int i = 0; i < jjtGetNumChildren(); i++ )
        {
            if( children[i] instanceof BNGModel )
                return (BNGModel)children[i];
        }
        return null;
    }

    public BNGDescription getDescription()
    {
        for( int i = 0; i < jjtGetNumChildren(); i++ )
        {
            if( children[i] instanceof BNGDescription )
                return (BNGDescription)children[i];
        }
        return null;
    }

    public BNGStart(int id)
    {
        super(id);
    }

    public BNGStart(BionetgenParser p, int id)
    {
        super(p, id);
    }
}
/* JavaCC - OriginalChecksum=2348d8f2261319049b697cffa6b7038b (do not edit this line) */
