version: "3"
services:
  mysql:
    image: mysql:5
    container_name: mysql-biouml2
    hostname: mysql-biouml2
    restart: unless-stopped
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
         - MYSQL_ROOT_PASSWORD=biouml
         - MYSQL_DATABASE=bioumlsupport2
         - MYSQL_USER=bioumlsupport2
         - MYSQL_PASSWORD=bioumlsupport2
    volumes:
      - ./dumps/bioumlsupport2.dump.sql:/docker-entrypoint-initdb.d/bioumlsupport2.dump.sql