/* Generated By:JJTree: Do not edit this line. GlycanMolecule.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Glycan,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.glycan.parser;

public class GlycanMolecule extends SimpleNode
{
    protected String binding = "";

    public String getBind()
    {
        return binding;
    }

    public void setBind(String binding)
    {
        this.binding = binding;
    }

    public String getFullName()
    {
        return binding + name;
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder(getFullName());
        int size = jjtGetNumChildren();
        for( int i = 0; i < size; i++ )
        {
            if( i != size - 1 && ! ( jjtGetChild(i) instanceof GlycanBranch ) )
                sb.append("(").append( ( (SimpleNode)jjtGetChild(i) ).toString()).append(")");
            else
                sb.append( ( (SimpleNode)jjtGetChild(i) ).toString());
        }
        return sb.toString();
    }

    public GlycanMolecule(int id)
    {
        super(id);
    }

    public GlycanMolecule(GlycanParser p, int id)
    {
        super(p, id);
    }
}
/* JavaCC - OriginalChecksum=7edf9d76c1e50e523a5bafa6b3fe8047 (do not edit this line) */
