/* Generated By:JJTree: Do not edit this line. GlycanBranch.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Glycan,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.glycan.parser;

public class GlycanBranch extends SimpleNode
{
    public GlycanBranch(int id)
    {
        super(id);
    }

    public GlycanBranch(GlycanParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder("(");
        for( int i = 0; i < jjtGetNumChildren(); i++ )
            sb.append( ( (SimpleNode)jjtGetChild(i) ).toString());
        sb.append(")");
        return sb.toString();
    }

}
/* JavaCC - OriginalChecksum=55c2292388ad2390e3575441b9c85061 (do not edit this line) */
