/* Generated By:JJTree&JavaCC: Do not edit this line. GlycanParserConstants.java */
package biouml.plugins.glycan.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GlycanParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CONNECTION = 5;
  /** RegularExpression Id. */
  int L_BRAKET = 6;
  /** RegularExpression Id. */
  int R_BRAKET = 7;
  /** RegularExpression Id. */
  int MOLECULE = 8;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "<CONNECTION>",
    "\"(\"",
    "\")\"",
    "<MOLECULE>",
  };

}
