/* Generated By:JJTree: Do not edit this line. GlycanTree.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Glycan,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.glycan.parser;

public class GlycanTree extends SimpleNode
{
    public GlycanTree(int id)
    {
        super(id);
    }

    public GlycanTree(GlycanParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        StringBuilder sb = new StringBuilder();
        for( int i = 0; i < jjtGetNumChildren(); i++ )
            sb.append( ( (SimpleNode)jjtGetChild(i) ).toString());
        return sb.toString();
    }
}
/* JavaCC - OriginalChecksum=a364a8ffd979a4a9e99dab8161c9bc20 (do not edit this line) */
