package biouml.plugins.wdl;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.developmentontheedge.beans.DynamicProperty;

import biouml.model.Compartment;
import biouml.model.Diagram;
import biouml.model.Node;
import biouml.plugins.wdl.diagram.WDLConstants;
import one.util.streamex.StreamEx;

public class NextFlowVelocityHelper extends WorkflowVelocityHelper
{
    private boolean isEntryScript = true;

    public NextFlowVelocityHelper(Diagram diagram)
    {
        super( diagram );
    }

    public NextFlowVelocityHelper(Diagram diagram, boolean isEntryScript)
    {
        super( diagram );
        this.isEntryScript = isEntryScript;
    }

    public Node getCallByOutput(Node node)
    {
        return node.edges().map( e -> e.getOtherEnd( node ) ).findAny( n -> WorkflowUtil.isCall( n ) ).orElse( null );
    }

    @Override
    public String getCommand(Compartment c)
    {
        String command = super.getCommand( c );
        command = command.replace( "$", "\\$" );
        command = command.replace( "~{", "${" );
        return command;
    }

    @Override
    public String getExpression(Node n)
    {
        String expression = super.getExpression( n );
        if( expression == null )
            return null;
        expression = expression.replace( "~{", "${" );
        return expression;
    }

    @Override
    public String getType(Node n)
    {
        return getNextFlowType( super.getType( n ) );
    }

    /**
     * Transforms WDL type to Nextflow type
     */
    private static String getNextFlowType(String wdlType)
    {
        switch( wdlType )
        {
            case "File":
            case "Array[File]":
                return "path";
            default:
                return "val";
        }
    }

    public String getExternalInput(Node n)
    {
        if( n == null )
            return "??";

        StringBuilder result = new StringBuilder();

        result.append( "params." );
        result.append( getName( n ) );
        String expression = getExpression( n );
        if( expression != null && !expression.isEmpty() )
        {
            result.append( " = " + expression );
        }
        return result.toString();
    }

    public String getVersion()
    {
        return WorkflowUtil.getVersion( diagram );
    }

    public String getCycleName(Compartment c)
    {
        Node cycleVarNode = WorkflowUtil.getCycleVariableNode( c );
        if( cycleVarNode == null )
            return null;
        Node source = WorkflowUtil.getSource( cycleVarNode );
        if( source == null )
            return null;
        return getName( source );
    }

    public String createChannelName(String input)
    {
        return input.replace( ".", "_" ) + "_ch";
    }

    public List<Node> getCallsScatters(Compartment compartment)
    {
        List<Node> result = new ArrayList<>();
        for( Node c : orderedCalls )
        {
            if( c.getParent().equals( compartment ) )
                result.add( c );
        }
        return result;
    }

    public String getInputName(Node n)
    {
        Node source = WorkflowUtil.getSource( n );
        if( source != null )
            n = source;
        String name = WorkflowUtil.getName( n );
        String type = WorkflowUtil.getType( n );
        if( WorkflowUtil.isExternalParameter( n ) )
        {
            String result = name;
            if( "File".equals( type ) )
                result = "channel.fromPath(" + result + ")";
            return result;
        }
        if( WorkflowUtil.isCall( n.getCompartment() ) )
            return getResultName( n.getCompartment() ) + "." + name;
        return name;
    }

    /**
     * @return name of the result generated by call associated with compartment
     */
    public String getResultName(Compartment c)
    {
        return "result_" + WorkflowUtil.getCallName( c );
    }

    public String getInputName(Compartment call)
    {
        List<Node> inputs = getOrderedInputs( call );
        if( inputs.isEmpty() )
            return "";

        if( WorkflowUtil.isCycle( call.getCompartment() ) )
            return "input_" + WorkflowUtil.getCallName( call );
        else
            return StreamEx.of( inputs ).map( n -> getFullName( WorkflowUtil.getSource( n ) ) ).joining( "," );
    }

    public String getFullName(Node node)
    {
        if( WorkflowUtil.isCall( node.getCompartment() ) )
        {
            return getResultName( node.getCompartment() ) + "." + getName( node );
        }
        return getName( node );
    }


    private String[] processCycleNodes(String mappingName, List<Node> nodes, StringBuffer defs, StringBuffer result, StringBuffer out,
            boolean insideCondition)
    {
        for( Node n : nodes )
        {
            if( WorkflowUtil.isExpression( n ) )
            {
                if( insideCondition )
                    defs.append( "\n    " + WorkflowUtil.getName( n ) + " = " + getExpression( n ) );
                else
                    defs.append( "\n    def " + WorkflowUtil.getName( n ) + " = " + getExpression( n ) );
                out.append( "\n  " + WorkflowUtil.getName( n ) + " = " + mappingName + "." + WorkflowUtil.getName( n ) );
                result.append( "\n    " + WorkflowUtil.getName( n ) + ": " + WorkflowUtil.getName( n ) );
            }
            else if( WorkflowUtil.isCall( n ) )
            {
                List<Node> inputs = WorkflowUtil.getOrderedInputs( (Compartment)n );
                result.append( "\n    " );
                result.append( WorkflowUtil.getCallName( n ) + "_input: tuple(" );
                result.append( StreamEx.of( inputs ).map( input -> WorkflowUtil.getExpression( input ) ).joining( ", " ) );
                result.append( ")" );
            }
            else if( WorkflowUtil.isConditional( n ) )
            {
                StringBuffer conditionalDefs = new StringBuffer();
                StringBuffer conditionalResult = new StringBuffer();
                StringBuffer conditionalOut = new StringBuffer();
                processCycleNodes( mappingName, WorkflowUtil.orderCallsScatters( (Compartment)n ), conditionalDefs, conditionalResult,
                        conditionalOut, true );
                String newDefs = conditionalDefs.toString();
                for( String newDef : newDefs.split( "\n" ) )
                {
                    if( !newDef.trim().isEmpty() )
                    {
                        newDef = newDef.substring( 0, newDef.indexOf( "=" ) - 1 ) + " = null";
                        defs.append( "\n    def " + newDef );
                    }
                }
                defs.append( "\n    if (" + WorkflowUtil.findCondition( (Compartment)n ) + ") {" );
                defs.append( conditionalDefs );
                result.append( conditionalResult.toString() );
                out.append( conditionalOut.toString() );
                defs.append( "\n    }" );
            }
        }
        return new String[] {defs.toString(), result.toString(), out.toString()};
    }

    /**
     *  cycle_inputs = range_i.combine(range_j).combine(range_k).multiMap* { i, j, k ->
     *      call_1_inputs: tuple(i, j)
     *      call_2_inputs: tuple(i, k)
     *  }
     */
    public String describeCycle(Compartment cycle)
    {
        List<Node> nodes = WorkflowUtil.orderCallsScatters( cycle );
        if( nodes.isEmpty() )
            return "";
        List<Compartment> cycles = WorkflowUtil.getParentCycles( cycle );
        String name = getCycleName( cycle );
        String mappingName = name + "_mapping";

        StringBuffer defs = new StringBuffer();
        StringBuffer result = new StringBuffer();
        StringBuffer out = new StringBuffer();
        String[] content = processCycleNodes( mappingName, nodes, defs, result, out, false );
        StringBuilder sb = new StringBuilder( "  " + mappingName + " = " );
        cycles.addFirst( cycle );
        cycles = cycles.reversed();
        List<String> cycleVars = StreamEx.of( cycles ).map( c -> getCycleVariable( c ) ).toList();
        List<String> cycleNames = StreamEx.of( cycles ).map( c -> getCycleName( c ) ).toList();
        sb.append( "toChannel(" + cycleNames.get( 0 ) + ")" );
        for( int i = 1; i < cycleNames.size(); i++ )
            sb.append( ".combine( " + cycleNames.get( i ) + ")" );

        sb.append( ".multiMap {" + StreamEx.of( cycleVars ).joining( ", " ) + " -> " );
        sb.append( content[0] );
        sb.append( "\n" );
        sb.append( content[1] );
        sb.append( "\n" );
        sb.append( "  }" );
        sb.append( "\n" );
        sb.append( content[2] );
        return sb.toString();
    }

    public String prepareInputs(Compartment call)
    {
        StringBuilder sb = new StringBuilder( "  " );

        List<Compartment> cycles = WorkflowUtil.getParentCycles( call );
        if( cycles.size() > 1 )
            return "";

        Compartment cycle = call.getCompartment();
        String cycleVar = getCycleVariable( cycle );
        String cycleName = getCycleName( cycle );
        Set<Node> arrayInputs = getArrayDepenedantInputs( cycleVar, call );
        for( Node input : arrayInputs )
        {
            String expression = WorkflowUtil.getExpression( input );
            if( ( cycleVar.equals( expression ) ) )
                sb.append( getName( input ) + " = " + cycleName );
            else if( expression.contains( "[" ) )
                sb.append( getName( input ) + " = " + expression.substring( 0, expression.indexOf( "[" ) ) );
            else
            {
                sb.append( ".map{" + cycleVar + " -> " + expression + "}" );
            }
            //            if( ! ( cycleVar.equals( expression ) ) )
            //                sb.append( ".map{" + cycleVar + " -> " + expression + "}" );
            sb.append( "\n" );
        }
        return sb.toString();
    }

    public String getCallInputName(Node input)
    {
        Compartment call = input.getCompartment();
        if( !isInsideCycle( call ) )
        {

            //            Node source = getSource( input );
            String result = getCallEmit( input );
            if( result == null )
                result = WorkflowUtil.getExpression( input );
            if( result == null || result.isEmpty() )
                result = "\"" + WDLConstants.NO_VALUE + "\"";
            //            if( source != null && isInsideCycle( source.getCompartment() ) )
            //                result += ".collect()";
            if( result.startsWith( "[" ) && result.endsWith( "]" ) )
                result = result.substring( 1, result.length() - 1 );
            return result;
        }
        else
        {
            List<Compartment> cycles = WorkflowUtil.getParentCycles( call );
            //            if( cycles.size() > 1 )
            //            {
            int pos = WorkflowUtil.getPosition( input );
            String cycleName = WorkflowUtil.getCycleName( cycles.get( 0 ) ); //split_inputs.add_inputs.map { it[0] },
            return cycleName + "_mapping." + WorkflowUtil.getCallName( call ) + "_input.map { it[" + pos + "] }";
            //            }

            //            Compartment cycle = call.getCompartment();
            //            String cycleVar = getCycleVariable( cycle );
            //            if( isArray( cycleVar, input ) )
            //                return getName( input );//getExpression(input).replaceAll("\\[\\s*"+cycleVar+"\\s*\\]", "");//getName( input ) + "_ch";
            //            else
            //            {
            //                String result = getCallEmit( input );
            //                if( result == null )
            //                    result = getExpression( input );
            //                if( result == null || result.isEmpty() )
            //                    result = "\"" + WDLConstants.NO_VALUE + "\"";
            //                if( result.startsWith( "[" ) && result.endsWith( "]" ) )
            //                    result = result.substring( 1, result.length() - 1 );
            //                return result;
            //            }
        }
    }

    //    public String processExpression(Node node)
    //    {
    //        Node source = getSource( node );
    //        if( source != null && isCall( source.getCompartment() ) )
    //        {
    //            
    //        }
    //    }

    public String getOutputExpression(Node node)
    {
        if( isInsideCycle( node ) )
        {

        }
        return getCallEmit( node );
    }

    public String getCallEmit(Node node)
    {
        String expression = getExpression( node );
        List<Node> sources = getSources( node );
        for( Node source : sources )
        {
            if( source != null && isCall( source.getCompartment() ) )
            {
                String result = getResultName( source.getCompartment() );
                String name = getCallName( source.getCompartment() );



                expression = expression.replace( name, result );
                //            boolean startBracket = expression.startsWith( "[" );
                //            expression = expression.substring( expression.indexOf( "." ) + 1 );
                //            if( startBracket )
                //                result = "[" + result;
                //            return result + "." + expression;
            }
        }
        return expression;
    }


    /**
     * replace all variables with 
     * e.g. i * 2 -> array.map { i->i*2}
     */
    public String processExpression(Node node)
    {
        String expression = getCallEmit( node );
        Compartment cycle = getClosestCycle( node );
        if( cycle == null )
            return expression;

        String variable = getCycleVariable( cycle );
        String name = getCycleName( cycle );
        //        if (expression.matches( name ))

        return name + ".map {" + variable + "->" + expression + " }";
    }

    public String getRuntimeProperty(Compartment process, String name)
    {
        DynamicProperty dp = process.getAttributes().getProperty( WDLConstants.RUNTIME_ATTR );
        if( dp == null || ! ( dp.getValue() instanceof String[] ) )
            return null;
        String[] options = (String[])dp.getValue();
        for( String option : options )
        {
            String[] parts = option.split( "#" );
            if( parts[0].equals( name ) )
            {
                return substituteVariables( parts[1], process );
            }
        }
        return null;
    }

    private String substituteVariables(String expression, Compartment process)
    {
        Map<String, String> replacements = new HashMap<>();
        List<String> variables = WorkflowUtil.findVariables( expression );
        for( String variable : variables )
        {
            String variableExpression = WorkflowUtil.findExpression( variable, process );
            if( variableExpression != null )
            {
                replacements.put( "~{" + variable + "}", variableExpression );
            }
        }
        for( Entry<String, String> e : replacements.entrySet() )
        {
            expression = expression.replace( e.getKey(), e.getValue() );
        }
        return expression;
    }

    public String getContainer(Compartment process)
    {
        return getRuntimeProperty( process, "docker" );
    }

    public String getCPUs(Compartment process)
    {
        return getRuntimeProperty( process, "cpu" );
    }

    public String getMemory(Compartment process)
    {
        return getRuntimeProperty( process, "memory" );
    }

    public String getMaxRetries(Compartment process)
    {
        return getRuntimeProperty( process, "maxRetries" );
    }

    public boolean shouldCollect(Compartment producer, Compartment consumer)
    {
        return true;
    }

    /**
     * Functions that should be imported from biouml_function.nf
     */
    public String getFunctions()
    {
        return "basename; sub; length; range; toChannel; getDefault; read_int; numerate; select_first";
    }

    public Compartment[] getImportedCalls()
    {
        return WorkflowUtil.getAllCalls( diagram ).stream().filter( c -> WorkflowUtil.getDiagramRef( c ) != null )
                .toArray( Compartment[]::new );
    }

    public String getImportedAlias(Compartment call)
    {
        return WorkflowUtil.getCallName( call );
    }



    public String writePrivateDeclaration(Declaration declaration)
    {
        String expression = declaration.getExpression();
        expression = expression.replace( "~{", "${" );
        return declaration.getName() + " = " + expression;
    }

    public Object getPrivateDeclarations(Compartment task)
    {
        return super.getBeforeCommand( task );
    }

    /**
     * @return names of all inputs for call which depends on scatter array
     */
    public Set<Node> getArrayDepenedantInputs(String cycleVar, Compartment call)
    {
        Set<Node> result = new HashSet<>();
        List<Node> inputs = WorkflowUtil.getInputs( call );
        for( Node input : inputs )
        {
            if( isArray( cycleVar, input ) )
                result.add( input );
        }
        return result;
    }

    public boolean isArray(String cycleVar, Node input)
    {
        return input.edges().map( e -> e.getInput() ).anyMatch( n -> WorkflowUtil.isCycleVariable( n ) );
    }

    public String getExternalParamaterName(Node input)
    {
        String result = "params." + getName( input );
        if( "File".equals( WorkflowUtil.getType( input ) ) )
            return "file(" + result + ")";
        //        else if( WorkflowUtil.getType( input ).contains( "Array" ) )
        //            return "toChannel(" + result + ").flatten()";
        else
            return result;
    }

    public boolean isNotEmpty()
    {
        return !WorkflowUtil.getAllCalls( diagram ).isEmpty();
    }

    public boolean isEntryScript()
    {
        return isEntryScript;
    }

}