/* Generated By:JJTree: Do not edit this line. AstConstant.java */
package ru.biosoft.math.model;

public class AstConstant extends SimpleNode
{
    public AstConstant(int id)
    {
        super(id);
    }

    private Object value;
    public Object getValue()
    {
        return value;
    }
    public void setValue(Object val)
    {
        value = val;
    }

    // name of predefined constant:
    private String name;
    public String getName()
    {
        return name;
    }
    /** Sets the name of the predefined constant. */
    public void setName(String name)
    {
        this.name = name;
    }

    @Override
    public String toString()
    {
        return "Constant: " + ( name != null ? name + "=" : "" ) + value;
    }
    @Override
    public AstConstant cloneAST()
    {
        AstConstant constant = new AstConstant(id);
        constant.name = name;
        constant.value = value;
        return constant;
    }

    @Override
    public boolean equals(Object obj)
    {
        if( this == obj )
            return true;
        if( obj == null )
            return false;
        if( getClass() != obj.getClass() )
            return false;
        final AstConstant other = (AstConstant)obj;
        if( name == null )
        {
            if( other.name != null )
                return false;
        }
        else if( !name.equals(other.name) )
            return false;
        if( value == null )
        {
            if( other.value != null )
                return false;
        }
        else if( !value.equals(other.value) )
            return false;
        return true;
    }

}
