package ru.biosoft.math.unitparser;

/* Generated By:JJTree: Do not edit this line. AstType.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

public
class AstType extends SimpleNode {
  public AstType(int id) {
    super(id);
  }

  public AstType(UnitParser p, int id) {
    super(p, id);
  }

  private String value;
  public String getValue()
  {
    return value;
  }
  public void setValue(String val)
  {
    value = val;
  }
}
/* JavaCC - OriginalChecksum=9605687e2ee74f1dc57e69f6f8acd434 (do not edit this line) */
