/* Generated By:JJTree: Do not edit this line. AstUnitNode.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package ru.biosoft.math.unitparser;

public
class AstUnitNode extends SimpleNode {
  public AstUnitNode(int id) {
    super(id);
  }

  public AstUnitNode(UnitParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b3a94c4ec31d8949a938eb37d5fc855 (do not edit this line) */
