/* Generated By:JavaCC: Do not edit this line. UnitParserTreeConstants.java Version 7.0.10 */
package ru.biosoft.math.unitparser;

public interface UnitParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTFUNNODE = 2;
  public int JJTUNITNODE = 3;
  public int JJTCONSTANT = 4;
  public int JJTTYPE = 5;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "FunNode",
    "UnitNode",
    "Constant",
    "Type",
  };
}
/* JavaCC - OriginalChecksum=2212d6a15f4fb868927927aa5716530e (do not edit this line) */
