/* Generated By:JavaCC: Do not edit this line. AntimonyNotationParserTreeConstants.java Version 7.0.10 */
package biouml.plugins.antimony.astparser_v2;

public interface AntimonyNotationParserTreeConstants
{
    public int JJTSTART = 0;
    public int JJTVOID = 1;
    public int JJTIMPORT = 2;
    public int JJTTEXT = 3;
    public int JJTFUNCTION = 4;
    public int JJTEOL = 5;
    public int JJTSEMICOLON = 6;
    public int JJTSYMBOL = 7;
    public int JJTREGULARFORMULAELEMENT = 8;
    public int JJTCOMMA = 9;
    public int JJTMODEL = 10;
    public int JJTGLOBAL = 11;
    public int JJTAS = 12;
    public int JJTIMPORTANNOTATION = 13;
    public int JJTEQUAL = 14;
    public int JJTPROPERTY = 15;
    public int JJTSINGLEPROPERTY = 16;
    public int JJTLIST = 17;
    public int JJTMAP = 18;
    public int JJTSET = 19;
    public int JJTUNIT = 20;
    public int JJTUNITFORMULA = 21;
    public int JJTDELETE = 22;
    public int JJTSYMBOLTYPE = 23;
    public int JJTSUBSTANCEONLY = 24;
    public int JJTVARORCONST = 25;
    public int JJTIN = 26;
    public int JJTEQUALZERO = 27;
    public int JJTEQUATION = 28;
    public int JJTSUBSYMBOL = 29;
    public int JJTCONNECTIONCONVERSIONFACTOR = 30;
    public int JJTCOLON = 31;
    public int JJTCOLONEQUAL = 32;
    public int JJTRATEEQUAL = 33;
    public int JJTAT = 34;
    public int JJTAFTER = 35;
    public int JJTELSE = 36;
    public int JJTASSERT = 37;
    public int JJTPRIORITY = 38;
    public int JJTUSEVALUESFROMTRIGGERTIME = 39;
    public int JJTPERSISTENT = 40;
    public int JJTTRIGGERINITIALVALUE = 41;
    public int JJTIS = 42;
    public int JJTSUBTYPE = 43;
    public int JJTHAS = 44;
    public int JJTRELATIONSHIPTYPE = 45;
    public int JJTREACTIONTITLE = 46;
    public int JJTPLUS = 47;
    public int JJTAND = 48;
    public int JJTOR = 49;
    public int JJTNOT = 50;
    public int JJTREACTANT = 51;
    public int JJTPRODUCT = 52;
    public int JJTSTOICHIOMETRY = 53;
    public int JJTREACTIONTYPE = 54;
    public int JJTCONVERSIONFACTOR = 55;
    public int JJTSPECIALFORMULA = 56;
    public int JJTLOCATEFUNCTION = 57;
    public int JJTCOMMENT = 58;


    public String[] jjtNodeName = {"Start", "void", "Import", "Text", "Function", "EOL", "Semicolon", "Symbol", "RegularFormulaElement",
            "Comma", "Model", "Global", "As", "ImportAnnotation", "Equal", "Property", "SingleProperty", "List", "Map", "Set", "Unit",
            "UnitFormula", "Delete", "SymbolType", "SubstanceOnly", "VarOrConst", "In", "EqualZero", "Equation", "SubSymbol",
            "ConnectionConversionFactor", "Colon", "ColonEqual", "RateEqual", "At", "After", "Else", "Assert", "Priority",
            "UseValuesFromTriggerTime", "Persistent", "TriggerInitialValue", "Is", "Subtype", "Has", "RelationshipType", "ReactionTitle",
            "Plus", "And", "Or", "Not", "Reactant", "Product", "Stoichiometry", "ReactionType", "ConversionFactor", "SpecialFormula",
            "LocateFunction", "Comment"};
}
/* JavaCC - OriginalChecksum=9632004d67c72ae2aea96b3402821c50 (do not edit this line) */
