/* Generated By:JJTree: Do not edit this line. AstAnd.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser_v2;

public class AstAnd extends AstFormulaElement
{
    public AstAnd(int id)
    {
        super(id);
    }

    public AstAnd(AntimonyNotationParser p, int id)
    {
        super(p, id);
    }

    public String toString()
    {
        return "&";
    }

}
/* JavaCC - OriginalChecksum=3ba2fb88a28698583e93b7ac0b8faf83 (do not edit this line) */
