/* Generated By:JJTree: Do not edit this line. AstAs.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser_v2;

public class AstAs extends SimpleNode
{
    public AstAs(int id)
    {
        super(id);
    }

    public AstAs(AntimonyNotationParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "as";
    }

    public AstSymbol getName()
    {
        for( int i = 0; i < this.jjtGetNumChildren(); i++ )
        {
            if( this.jjtGetChild(i) instanceof AstSymbol )
                return (AstSymbol)this.jjtGetChild(i);
        }
        return null;
    }
}
/* JavaCC - OriginalChecksum=d30483202d331d70de0d454f3ddefb2e (do not edit this line) */
