/* Generated By:JJTree: Do not edit this line. AstColon.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser_v2;

public class AstColon extends SimpleNode
{
    public AstColon(int id)
    {
        super(id);
    }

    public AstColon(AntimonyNotationParser p, int id)
    {
        super(p, id);
    }

    public String toString()
    {
        return ":";
    }

}
/* JavaCC - OriginalChecksum=af6ca96a0a2a2c77c5d96b0c684ab18e (do not edit this line) */
