/* Generated By:JJTree: Do not edit this line. AstIs.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser_v2;

public class AstIs extends SimpleNode
{
    public AstIs(int id)
    {
        super(id);
    }

    public AstIs(AntimonyNotationParser p, int id)
    {
        super(p, id);
    }

    public String getDisplayName()
    {
        for( int i = 0; i < this.jjtGetNumChildren(); i++ )
            if( this.jjtGetChild(i) instanceof AstText )
                return ( ( (AstText)this.jjtGetChild(i) ).getText() ).replaceAll("\"", "");
        return null;
    }

    public AstSymbol getSynchronizedElement()
    {
        Node astNode = this.jjtGetChild(0);
        if( astNode != null && astNode instanceof AstSymbol )
            return (AstSymbol)astNode;
        return null;
    }

    public String toString()
    {
        return "is";
    }

    public void setDisplayName(String name)
    {
        for( int i = 0; i < this.jjtGetNumChildren(); i++ )
            if( this.jjtGetChild(i) instanceof AstText )
                ( (AstText)this.jjtGetChild(i) ).setText("\"" + name + "\"");
    }
}
/* JavaCC - OriginalChecksum=609e45f0f8e5897b596ed476e0aa5ca2 (do not edit this line) */
