/* Generated By:JJTree: Do not edit this line. AstImportAnnotation.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser_v2;

public class AstImportAnnotation extends SimpleNode
{

    private String annotationType;

    public AstImportAnnotation(int id)
    {
        super(id);
    }

    public AstImportAnnotation(AntimonyNotationParser p, int id)
    {
        super(p, id);
    }

    public void setAnnotationType(String annotationType)
    {
        this.annotationType = annotationType;
    }

    public String getAnnotationType()
    {
        return annotationType;
    }

    public String toString()
    {
        return "@import " + annotationType;
    }

    public String getPath()
    {
        for( Node node : getChildren() )
            if( node instanceof AstText )
                return ( (AstText)node ).getText().replace("\"", "");

        return "";
    }

}
/* JavaCC - OriginalChecksum=102cc930c58b5821c05ca10cb766d2c2 (do not edit this line) */
