/* Generated By:JJTree: Do not edit this line. AstLocateFunction.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser_v2;

import java.util.HashMap;
import java.util.Map;

public class AstLocateFunction extends SimpleNode
{
    Map<String, String> properties;
    public AstLocateFunction(int id)
    {
        super(id);
        this.properties = new HashMap<String, String>();
    }

    public AstLocateFunction(AntimonyNotationParser p, int id)
    {
        super(p, id);
    }

    public void addProperty(String propertyName, String value)
    {
        properties.put(propertyName, value);
    }

    public String getProperty(String propertyName)
    {
        return properties.get(propertyName);
    }

    @Override
    public String toString()
    {
        return "locate";
    }

}
/* JavaCC - OriginalChecksum=a960ee6e954c57a8a3550310503b8246 (do not edit this line) */
