/* Generated By:JJTree: Do not edit this line. AstTriggerInitialValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser_v2;

public class AstTriggerInitialValue extends SimpleNode
{
    public AstTriggerInitialValue(int id)
    {
        super(id);
    }

    public AstTriggerInitialValue(AntimonyNotationParser p, int id)
    {
        super(p, id);
    }

    public boolean getValue() throws ParseException
    {
        for( int i = 0; i < this.jjtGetNumChildren(); i++ )
            if( this.jjtGetChild(i) instanceof AstRegularFormulaElement )
            {
                return Boolean.parseBoolean( ( (AstRegularFormulaElement)this.jjtGetChild(i) ).toString());
            }
        throw new ParseException("Invalid AST tree structure at line: " + firstToken.beginLine + ", column: " + firstToken.beginColumn
                + ". Was expected one of: 'true', 'false'");
    }

    public void setValue(boolean value)
    {
        for( int i = 0; i < this.jjtGetNumChildren(); i++ )
            if( this.jjtGetChild(i) instanceof AstRegularFormulaElement )
            {
                ( (AstRegularFormulaElement)this.jjtGetChild(i) ).setElement(value);
                break;
            }
    }

    public String toString()
    {
        return "t0";
    }
}
/* JavaCC - OriginalChecksum=afa322fca407e4b18aeff5ec8faf8762 (do not edit this line) */
