/* Generated By:JJTree: Do not edit this line. Node.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.antimony.astparser_v2;

/* All AST nodes must implement this interface.  It provides basic
   machinery for constructing the parent and child relationships
   between nodes. */

public interface Node
{

    /** This method is called after the node has been made the current
      node.  It indicates that child nodes can now be added to it. */
    public void jjtOpen();

    /** This method is called after all the child nodes have been
      added. */
    public void jjtClose();

    /** This pair of methods are used to inform the node of its
      parent. */
    public void jjtSetParent(Node n);
    public Node jjtGetParent();

    /** This method tells the node to add its argument to the node's
      list of children.  */
    public void jjtAddChild(Node n, int i);

    /** This method returns a child node.  The children are numbered
       from zero, left to right. */
    public Node jjtGetChild(int i);

    /** Return the number of children the node has. */
    public int jjtGetNumChildren();

    public String toAntimonyString();

    /** add a child like last element*/
    public void addAsLast(Node child);

    /** add a child with a shift to the right*/
    public void addWithDisplacement(Node child, int i);

    public void removeChild(int i);

    /**
     * remove astNode
     * @return index of node in parent
     */
    public int remove();

    /**
     * returns index of the given node in the children array
     * @param node
     * @return -1 if given node does not belong to current node
     */
    public int findIndex(Node node);

    /**
     * returns true if this node is highlighted
     * @return
     */
    public boolean isHighlight();
}
/* JavaCC - OriginalChecksum=eab3bd38184fde190af12ecd72b1feb0 (do not edit this line) */
