/* Generated By:JJTree: Do not edit this line. AstArray.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public
class AstArray extends SimpleNode {
  public AstArray(int id) {
    super(id);
  }

  public AstArray(WDLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bba5ce546a992718ec72de4965e3721d (do not edit this line) */
