/* Generated By:JJTree: Do not edit this line. AstAs.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstAs extends SimpleNode
{
    public AstAs(int id)
    {
        super(id);
    }

    public AstAs(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "as";
    }

    public String getAlias()
    {
        for( Node child : getChildren() )
        {
            if( child instanceof AstSymbol )
                return ( (AstSymbol)child ).getName();
        }
        return null;
    }

}
/* JavaCC - OriginalChecksum=5e47ab6f55b64eee11b9b973a741d59d (do not edit this line) */
