/* Generated By:JJTree: Do not edit this line. AstBashString.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstBashString extends SimpleNode
{
    private String command;

    public AstBashString(int id)
    {
        super(id);
    }

    public AstBashString(WDLParser p, int id)
    {
        super(p, id);
    }

    public void setCommand(String text)
    {
        this.command = text;

    }
    
    @Override
    public void jjtAddChild(Node n, int i)
    {
        super.jjtAddChild( n, i );
    }
    
    public String getCommand()
    {
        StringBuilder result = new StringBuilder("");
        for( int i = 0; i < this.jjtGetNumChildren(); i++ )
        {
            result.append(jjtGetChild(i).toString());
        }
        return result.toString();
    }

    @Override
    public String toString()
    {
        return "";
    }

}
/* JavaCC - OriginalChecksum=207bb284d064e419f9fb5850dc728b3e (do not edit this line) */
