/* Generated By:JJTree: Do not edit this line. AstComma.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstComma extends SimpleNode
{
    public AstComma(int id)
    {
        super(id);
    }

    public AstComma(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return ",";
    }

}
/* JavaCC - OriginalChecksum=08b7891886b1e36a3ef1363e60bbb256 (do not edit this line) */
