/* Generated By:JJTree: Do not edit this line. AstConstructor.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstConstructor extends SimpleNode
{
    private String name;

    public AstConstructor(int id)
    {
        super(id);
    }

    public AstConstructor(WDLParser p, int id)
    {
        super(p, id);
    }


    public void setName(String name)
    {
        this.name = name;
    }

    @Override
    public String toString()
    {
        return name;
    }

}
/* JavaCC - OriginalChecksum=92271b7b656cbe39e5e7d24b33e6bf06 (do not edit this line) */
