/* Generated By:JJTree: Do not edit this line. AstEq.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public
class AstEq extends SimpleNode {
  public AstEq(int id) {
    super(id);
  }

  public AstEq(WDLParser p, int id) {
    super(p, id);
  }
  
  @Override
  public String toString()
  {
      return "==";
  }
}
/* JavaCC - OriginalChecksum=d4d34118abe3127928216b547f984817 (do not edit this line) */
