/* Generated By:JJTree: Do not edit this line. AstElse.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstElse extends SimpleNode
{
    public AstElse(int id)
    {
        super(id);
    }

    public AstElse(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "else";
    }
}
/* JavaCC - OriginalChecksum=ca8bec1b18a1b69f410def49635a5e68 (do not edit this line) */
