/* Generated By:JJTree: Do not edit this line. AstEOL.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstEOL extends SimpleNode
{
    public AstEOL(int id)
    {
        super(id);
    }

    public AstEOL(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "\n";
    }
}
/* JavaCC - OriginalChecksum=beadc4c20ac886b02b53eeab484c87b9 (do not edit this line) */
