/* Generated By:JJTree: Do not edit this line. AstEqual.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstEqual extends SimpleNode
{
    public AstEqual(int id)
    {
        super(id);
    }

    public AstEqual(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "=";
    }

}
/* JavaCC - OriginalChecksum=145484950812b943397e7216369db6d5 (do not edit this line) */
