/* Generated By:JJTree: Do not edit this line. AstImport.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstImport extends SimpleNode
{
    public AstImport(int id)
    {
        super(id);
    }

    public AstImport(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "import "+getSource()+" as "+getAlias();
    }
    
    public String getSource()
    {
        return this.getChildren()[0].toString();
    }
    
    public String getAlias()
    {
        return ((AstAs)this.getChildren()[1]).getAlias();
    }

}
/* JavaCC - OriginalChecksum=405d080581cfd8280e8dd37fa4c26cb4 (do not edit this line) */
