/* Generated By:JJTree: Do not edit this line. AstIn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstIn extends SimpleNode
{
    public AstIn(int id)
    {
        super(id);
    }

    public AstIn(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "in";
    }

}
/* JavaCC - OriginalChecksum=0e0ccaae3c88ee7a2341bc17689b32ec (do not edit this line) */
