/* Generated By:JJTree: Do not edit this line. AstInput.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;


public class AstInput extends AstScope
{
    public AstInput(int id)
    {
        super(id);
    }

    public AstInput(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "input";
    }
}
/* JavaCC - OriginalChecksum=c8ee4fab0fce2d77ff66cbc0025ad82b (do not edit this line) */
