/* Generated By:JJTree: Do not edit this line. AstKeyValue.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstKeyValue extends SimpleNode
{
    private String keyName;

    public AstKeyValue(int id)
    {
        super(id);
    }

    public AstKeyValue(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return keyName;
    }

    public void setKey(String key)
    {
        this.keyName = key;
    }
    
    public String getKey()
    {
        return keyName;
    }

}
/* JavaCC - OriginalChecksum=c2845a5d77a393f42d3459c79b73bc44 (do not edit this line) */
