/* Generated By:JJTree: Do not edit this line. AstMeta.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstMeta extends SimpleNode
{
    public AstMeta(int id)
    {
        super(id);
    }

    public AstMeta(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "meta";
    }

}
/* JavaCC - OriginalChecksum=172d77f700da755191d864f6b1768170 (do not edit this line) */
