/* Generated By:JJTree: Do not edit this line. AstMap.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstMap extends SimpleNode
{
    public AstMap(int id)
    {
        super(id);
    }

    public AstMap(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "";
    }

}
/* JavaCC - OriginalChecksum=ff62e9afce6e0aebf8c9ec3ae2014302 (do not edit this line) */
