/* Generated By:JJTree: Do not edit this line. AstMetaFormulaElement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstMetaFormulaElement extends AstFormulaElement
{
    public AstMetaFormulaElement(int id)
    {
        super(id);
    }

    public AstMetaFormulaElement(WDLParser p, int id)
    {
        super(p, id);
    }

}
/* JavaCC - OriginalChecksum=072896322f1902f4b4d301689fc6cebd (do not edit this line) */
