/* Generated By:JJTree: Do not edit this line. AstNone.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public
class AstNone extends SimpleNode {
  public AstNone(int id) {
    super(id);
  }

  public AstNone(WDLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a675bcbfdd71e756e6aabccf7b924245 (do not edit this line) */
