/* Generated By:JJTree: Do not edit this line. AstOutput.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstOutput extends AstScope
{
    public AstOutput(int id)
    {
        super(id);
    }

    public AstOutput(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "output";
    }

}
/* JavaCC - OriginalChecksum=bfc2ccf2348431f99f7176c92799030e (do not edit this line) */
