/* Generated By:JJTree: Do not edit this line. AstRuntime.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstRuntime extends SimpleNode
{

    public AstRuntime(int id)
    {
        super(id);
    }

    public AstRuntime(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "runtime";
    }
}
/* JavaCC - OriginalChecksum=85d5380cee921c610075e40c0ecaa8bc (do not edit this line) */
