/* Generated By:JJTree: Do not edit this line. AstRuntime.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

import java.util.HashMap;
import java.util.Map;

public class AstRuntime extends SimpleNode
{

    public AstRuntime(int id)
    {
        super( id );
    }

    public AstRuntime(WDLParser p, int id)
    {
        super( p, id );
    }

    @Override
    public String toString()
    {
        return "runtime";
    }

    public Map<String, String> getValues()
    {
        Map<String, String> result = new HashMap<>();
        for( int i = 0; i < jjtGetNumChildren(); i++ )
        {
            Node child = jjtGetChild( i );
            if( child instanceof AstRegularFormulaElement && ( (AstRegularFormulaElement)child ).firstToken.toString().equals( ":" ) )
            {
                String key = jjtGetChild( i - 1 ).toString();
                String value = jjtGetChild( i + 1 ).toString();
                result.put( key, value );
            }
        }
        return result;
    }
}
/* JavaCC - OriginalChecksum=85d5380cee921c610075e40c0ecaa8bc (do not edit this line) */
