/* Generated By:JJTree: Do not edit this line. AstSymbol.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstSymbol extends SimpleNode
{
    String name;
    public AstSymbol(int id)
    {
        super(id);
    }

    public AstSymbol(WDLParser p, int id)
    {
        super(p, id);
    }

    public void setName(String name)
    {
        this.name = name;

    }

    public String getName()
    {
        return name;
    }

    @Override
    public String toString()
    {
        StringBuilder result = new StringBuilder( firstToken.image );
        if( children != null )
        {
            for( Node node : children )
                result.append( node.toString() );
        }
        return result.toString();
    }
}
/* JavaCC - OriginalChecksum=037068126b1436137c463e10dbfeebc9 (do not edit this line) */
