/* Generated By:JJTree: Do not edit this line. AstStart.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstStart extends AstScope
{
    String version;
    boolean workflowExist = false;
    public AstStart(int id)
    {
        super(id);
    }

    public AstStart(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "";
    }

    public String getVersion()
    {
        return version;
    }

    public void setWorkflowExist(boolean workflowExist)
    {
        this.workflowExist = workflowExist;
    }

    public boolean workflowExist()
    {
        return workflowExist;
    }

}
/* JavaCC - OriginalChecksum=c83fff2e7098fd8a135fa01753d278e9 (do not edit this line) */
