/* Generated By:JJTree: Do not edit this line. AstThen.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstThen extends SimpleNode
{
    public AstThen(int id)
    {
        super(id);
    }

    public AstThen(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "then";
    }

}
/* JavaCC - OriginalChecksum=30e3ff6a70e41956aa227d1b71b23a67 (do not edit this line) */
