/* Generated By:JJTree: Do not edit this line. AstText.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstText extends SimpleNode
{
    String text;
    public AstText(int id)
    {
        super(id);
    }

    public AstText(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return getText();
    }

    public String getText()
    {
        return text;
    }

    public void setText(String text)
    {
        this.text = text;
    }

}
/* JavaCC - OriginalChecksum=3df6a94849d5489111edb63ef032fe42 (do not edit this line) */
