/* Generated By:JJTree: Do not edit this line. AstType.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstType extends SimpleNode
{
    private String type;
    public AstType(int id)
    {
        super( id );
    }

    public AstType(WDLParser p, int id)
    {
        super( p, id );
    }

    @Override
    public String toString()
    {
        StringBuilder builder = new StringBuilder();
        builder.append( firstToken.image );
        if( this.children != null )
        {
            for( Node node : children )
            {
                builder.append( node.toString() );
            }
        }
        return builder.toString();
    }
}
/* JavaCC - OriginalChecksum=06c3d61521507f24f7df91db368906bf (do not edit this line) */
