/* Generated By:JJTree: Do not edit this line. AstTask.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import one.util.streamex.StreamEx;

public class AstTask extends AstScope
{
    private String name;

    public AstTask(int id)
    {
        super( id );
    }

    public AstTask(WDLParser p, int id)
    {
        super( p, id );
    }

    @Override
    public String toString()
    {
        return "task";
    }

    public String getName()
    {
        return name;
    }

    public void setName(String name)
    {
        this.name = name;
    }

    public List<AstDeclaration> getBeforeCommand()
    {
        List<AstDeclaration> result = new ArrayList<>();
        for( Node node : children )
        {
            if( node instanceof AstCommand )
               break;

            if( node instanceof AstDeclaration )
                result.add( (AstDeclaration)node );

        }
        return result;
    }

    public String getCommand()
    {
        return StreamEx.of( children ).select( AstCommand.class ).map( n -> n.getBashString().getCommand() ).findAny().orElse( null );
        //        for (Node node: children)
        //        {
        //            if (node instanceof AstCommand)
        //            {
        //                return ((AstCommand)node).getBashString().getCommand();
        //            }
        //        }
        //        return null;
    }

    public Map<String, String> getRuntime()
    {
        for( Node node : children )
        {
            if( node instanceof AstRuntime )
            {
                return ( (AstRuntime)node ).getValues();
            }
        }
        return new HashMap<String, String>();
    }

    public AstInput getInput()
    {
        for( Node node : children )
        {
            if( node instanceof AstInput )
                return (AstInput)node;
        }
        return null;
    }

    public AstOutput getOutput()
    {
        for( Node node : children )
        {
            if( node instanceof AstOutput )
                return (AstOutput)node;
        }
        return null;
    }

}
/* JavaCC - OriginalChecksum=c7f77334a3b2603c0e8c8a585e357b09 (do not edit this line) */
