/* Generated By:JJTree: Do not edit this line. AstVersion.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=Ast,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package biouml.plugins.wdl.parser;

public class AstVersion extends SimpleNode
{
    public AstVersion(int id)
    {
        super(id);
    }

    public AstVersion(WDLParser p, int id)
    {
        super(p, id);
    }

    @Override
    public String toString()
    {
        return "version";
    }

}
/* JavaCC - OriginalChecksum=9434e5947263e4cd4bc88044136ad5ab (do not edit this line) */
