/* Generated By:JavaCC: Do not edit this line. WDLParserTreeConstants.java Version 7.0.11 */
package biouml.plugins.wdl.parser;

public interface WDLParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTVERSION = 2;
  public int JJTTASK = 3;
  public int JJTREGULARFORMULAELEMENT = 4;
  public int JJTMETA = 5;
  public int JJTMETAFORMULAELEMENT = 6;
  public int JJTARRAY = 7;
  public int JJTCOMMA = 8;
  public int JJTMAP = 9;
  public int JJTKEYVALUE = 10;
  public int JJTCOLON = 11;
  public int JJTWORKFLOW = 12;
  public int JJTSCATTER = 13;
  public int JJTIN = 14;
  public int JJTCONDITIONAL = 15;
  public int JJTCOMMAND = 16;
  public int JJTBASHSTRING = 17;
  public int JJTCALL = 18;
  public int JJTSYMBOL = 19;
  public int JJTINPUT = 20;
  public int JJTSUBSYMBOL = 21;
  public int JJTEQUAL = 22;
  public int JJTRUNTIME = 23;
  public int JJTHINTS = 24;
  public int JJTEOL = 25;
  public int JJTOUTPUT = 26;
  public int JJTSTRUCT = 27;
  public int JJTDECLARATION = 28;
  public int JJTTYPE = 29;
  public int JJTARRAYTYPE = 30;
  public int JJTPAIRTYPE = 31;
  public int JJTMAPTYPE = 32;
  public int JJTTERNARY = 33;
  public int JJTTHEN = 34;
  public int JJTELSE = 35;
  public int JJTEXPRESSION = 36;
  public int JJTNONE = 37;
  public int JJTCONTAINERELEMENT = 38;
  public int JJTCONSTRUCTOR = 39;
  public int JJTIMPORT = 40;
  public int JJTALIAS = 41;
  public int JJTTEXT = 42;
  public int JJTFUNCTION = 43;
  public int JJTAS = 44;
  public int JJTPAIR = 45;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Version",
    "Task",
    "RegularFormulaElement",
    "Meta",
    "MetaFormulaElement",
    "Array",
    "Comma",
    "Map",
    "KeyValue",
    "Colon",
    "Workflow",
    "Scatter",
    "In",
    "Conditional",
    "Command",
    "BashString",
    "Call",
    "Symbol",
    "Input",
    "SubSymbol",
    "Equal",
    "Runtime",
    "Hints",
    "EOL",
    "Output",
    "Struct",
    "Declaration",
    "Type",
    "ArrayType",
    "PairType",
    "MapType",
    "Ternary",
    "Then",
    "Else",
    "Expression",
    "None",
    "ContainerElement",
    "Constructor",
    "Import",
    "Alias",
    "Text",
    "Function",
    "As",
    "Pair",
  };
}
/* JavaCC - OriginalChecksum=b2d144a2a2279678e431864c0cf3c2c3 (do not edit this line) */
