/* Generated By:JJTree&JavaCC: Do not edit this line. WDLParserConstants.java */
package biouml.plugins.wdl.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface WDLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EOL = 1;
  /** RegularExpression Id. */
  int COMMAND = 5;
  /** RegularExpression Id. */
  int PARAMETER_META = 6;
  /** RegularExpression Id. */
  int META = 7;
  /** RegularExpression Id. */
  int RUNTIME = 8;
  /** RegularExpression Id. */
  int HINTS = 9;
  /** RegularExpression Id. */
  int REQUIREMENTS = 10;
  /** RegularExpression Id. */
  int COMMAND_HEREDOC_START = 11;
  /** RegularExpression Id. */
  int COMMAND_START = 12;
  /** RegularExpression Id. */
  int START = 13;
  /** RegularExpression Id. */
  int COMMAND_END = 14;
  /** RegularExpression Id. */
  int COMMAND_HEREDOC_END = 15;
  /** RegularExpression Id. */
  int ANY = 16;
  /** RegularExpression Id. */
  int TASK = 17;
  /** RegularExpression Id. */
  int WORKFLOW = 18;
  /** RegularExpression Id. */
  int VERSION = 19;
  /** RegularExpression Id. */
  int INPUT = 20;
  /** RegularExpression Id. */
  int OUTPUT = 21;
  /** RegularExpression Id. */
  int PRIMITIVE_TYPE = 22;
  /** RegularExpression Id. */
  int ARRAY = 23;
  /** RegularExpression Id. */
  int NONE = 24;
  /** RegularExpression Id. */
  int OBJECT_TYPE = 25;
  /** RegularExpression Id. */
  int PAIR = 26;
  /** RegularExpression Id. */
  int MAP = 27;
  /** RegularExpression Id. */
  int ALIAS = 28;
  /** RegularExpression Id. */
  int AS = 29;
  /** RegularExpression Id. */
  int CALL = 30;
  /** RegularExpression Id. */
  int ELSE = 31;
  /** RegularExpression Id. */
  int TRUE_OR_FALSE = 32;
  /** RegularExpression Id. */
  int IF = 33;
  /** RegularExpression Id. */
  int IN = 34;
  /** RegularExpression Id. */
  int IMPORT = 35;
  /** RegularExpression Id. */
  int OBJECT = 36;
  /** RegularExpression Id. */
  int SCATTER = 37;
  /** RegularExpression Id. */
  int STRUCT = 38;
  /** RegularExpression Id. */
  int THEN = 39;
  /** RegularExpression Id. */
  int NULL = 40;
  /** RegularExpression Id. */
  int DOT = 41;
  /** RegularExpression Id. */
  int AND = 42;
  /** RegularExpression Id. */
  int OR = 43;
  /** RegularExpression Id. */
  int NOT = 44;
  /** RegularExpression Id. */
  int BRAKET_L = 45;
  /** RegularExpression Id. */
  int BRAKET_R = 46;
  /** RegularExpression Id. */
  int COLON = 47;
  /** RegularExpression Id. */
  int EQUAL = 48;
  /** RegularExpression Id. */
  int PLUS = 49;
  /** RegularExpression Id. */
  int MINUS = 50;
  /** RegularExpression Id. */
  int SEMICOLON = 51;
  /** RegularExpression Id. */
  int COMMA = 52;
  /** RegularExpression Id. */
  int QUESTION_MARK = 53;
  /** RegularExpression Id. */
  int TEXT_STRING = 54;
  /** RegularExpression Id. */
  int OCTAL_ESCAPE = 55;
  /** RegularExpression Id. */
  int HEX_ESCAPE = 56;
  /** RegularExpression Id. */
  int UNICODE = 57;
  /** RegularExpression Id. */
  int LETTER = 58;
  /** RegularExpression Id. */
  int DIGIT = 59;
  /** RegularExpression Id. */
  int SYMBOL = 60;
  /** RegularExpression Id. */
  int INTEGER = 61;
  /** RegularExpression Id. */
  int TRIANGULAR_BRACKET_L = 62;
  /** RegularExpression Id. */
  int TRIANGULAR_BRACKET_R = 63;
  /** RegularExpression Id. */
  int SQUARE_BRACKET_L = 64;
  /** RegularExpression Id. */
  int SQUARE_BRACKET_R = 65;
  /** RegularExpression Id. */
  int OPERATOR = 66;
  /** RegularExpression Id. */
  int STAR = 67;
  /** RegularExpression Id. */
  int EXPONENT = 68;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 69;
  /** RegularExpression Id. */
  int BRACE_L = 70;
  /** RegularExpression Id. */
  int BRACE_R = 71;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int BASH_STRING = 1;
  /** Lexical state. */
  int BASH_COMMAND = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<EOL>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 4>",
    "\"command\"",
    "\"parameter_meta\"",
    "\"meta\"",
    "\"runtime\"",
    "\"hints\"",
    "\"requirements\"",
    "\"<<<\"",
    "<COMMAND_START>",
    "<START>",
    "<COMMAND_END>",
    "\">>>\"",
    "<ANY>",
    "\"task\"",
    "\"workflow\"",
    "\"version\"",
    "\"input\"",
    "\"output\"",
    "<PRIMITIVE_TYPE>",
    "\"Array\"",
    "\"None\"",
    "\"Object\"",
    "\"Pair\"",
    "\"Map\"",
    "\"alias\"",
    "\"as\"",
    "\"call\"",
    "\"else\"",
    "<TRUE_OR_FALSE>",
    "\"if\"",
    "\"in\"",
    "\"import\"",
    "\"object\"",
    "\"scatter\"",
    "\"struct\"",
    "\"then\"",
    "\"null\"",
    "\".\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\";\"",
    "\",\"",
    "\"?\"",
    "<TEXT_STRING>",
    "<OCTAL_ESCAPE>",
    "<HEX_ESCAPE>",
    "<UNICODE>",
    "<LETTER>",
    "<DIGIT>",
    "<SYMBOL>",
    "<INTEGER>",
    "\"<\"",
    "\">\"",
    "\"[\"",
    "\"]\"",
    "<OPERATOR>",
    "\"*\"",
    "<EXPONENT>",
    "<FLOATING_POINT_LITERAL>",
    "\"{\"",
    "\"}\"",
  };

}
