/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
package ru.biosoft.math.parser;

public interface ParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTFUNNODE = 2;
  public int JJTFUNCTIONDECLARATION = 3;
  public int JJTVARNODE = 4;
  public int JJTPIECEWISE = 5;
  public int JJTPIECE = 6;
  public int JJTCONSTANT = 7;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "FunNode",
    "FunctionDeclaration",
    "VarNode",
    "Piecewise",
    "Piece",
    "Constant",
  };
}
/* JavaCC - OriginalChecksum=5a171dd12a87fd61e1fc37357e081832 (do not edit this line) */
