version 1.0


task generate_file {
  input {
    Int index
  }

  command <<<
    echo "This is file number ~{index}" > output_~{index}.txt
  >>>

  output {
    File out_file = "output_~{index}.txt"
  }
}

task process_file {

  input {
    File input_file
    String output_name
  }

  command {
    echo "Processed file: ~{input_file}" >> ~{output_name}
    cp ~{input_file} ~{output_name}
  }

  output {
    File output_file = output_name
  }
}

workflow file_chain_wdl {

  input {
     Array[Int] indices = [1,3,4]
     Int index = 2
  }

  scatter (i in indices) {
    call generate_file {
       input: index = i
    }
  }

  call process_file  {
    input:
      input_file = generate_file.out_file[index],
      output_name = "res_2"
  }

  output {
    File processed_file = process_file.output_file
  }

  meta {
    title: "Array select 2"
    description: "Tests selecting element generated by cycle."
  }
}