package biouml.plugins.sbgn.title;

public enum LexemeType
{
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS,
    COLON,
    LEFT_BRACKET, RIGHT_BRACKET,
    LEFT_SQUARE_BRACKET, RIGHT_SQUARE_BRACKET,
    INTEGER,
    STRING,
    ANGLE_BRACKET_LEFT, ANGLE_BRACKET_RIGHT 
}