version 1.0

task generate_file_a {
  input {
    Int index
  }
  command {
    echo "File A: ~{index}" > output_a_~{index}.txt
  }
  output {
    File outFile = "output_a_~{index}.txt"
  }
}

task generate_file_b {
  input {
    Int index
  }
  command {
    echo "File B: ~{index}" > output_b_~{index}.txt
  }
  output {
    File outFile = "output_b_~{index}.txt"
  }
}

task process_files {
  input {
    File fileA
    File fileB
  }
  command {
    cat ~{fileA} ~{fileB} > combined_~{basename(fileA)}_~{basename(fileB)}.txt
  }
  output {
    File combinedFile = "combined_~{basename(fileA)}_~{basename(fileB)}.txt"
  }
}

workflow simple_generate_and_process {
  input {
    Array[Int] arrayA = [1,2,3]
    Array[Int] arrayB = [4,5,6]
  }

  scatter(i in range(length(arrayA))) {
    call generate_file_a {
      input:
        index = arrayA[i]
    }
  }

  scatter(j in range(length(arrayB))) {
    call generate_file_b {
      input:
        index = arrayB[j]
    }
  }

  scatter( k in range(length(arrayA)) ) {
    call process_files {
      input:
        fileA = generate_file_a.outFile[k],
        fileB = generate_file_b.outFile[k]
    }
  }

  output {
    Array[File] results = process_files.combinedFile
  }
  
  meta {
    title: "Two inputs 2"
    description: "Two arrays of files generated by calls are merged and passed to third call."
  }
}