name: Tests in main branch

# Trigger this workflow on pushes to the main branch or any pull requests
on:
  push:
    branches:
      - main

# Define the jobs that run in this workflow
jobs:
  build:

    # The environment where this job will run (Ubuntu is common for Maven)
    runs-on: ubuntu-latest

    # Steps to run
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install private BioUML libraries
      run: |
        ./install_all_old_jars.sh 

    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    - name: Run tests
      run: mvn -B test
